# Generated by Django 4.2 on 2023-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_publicacion_isbn13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='tipo',
            field=models.CharField(choices=[('Libro', 'Libro'), ('Articulo', 'Articulo')], default='Libro', max_length=8),
        ),
    ]
