# Generated by Django 4.2 on 2023-04-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_publicacion_revista_alter_publicacion_autores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='volumen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autores',
            field=models.ManyToManyField(to='biblioteca.autor', verbose_name='Autor/es'),
        ),
    ]
